# Generated by Django 4.1.4 on 2022-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filmuser',
            constraint=models.UniqueConstraint(fields=('film', 'user'), name='algunnombre'),
        ),
    ]
